# Generated by Django 4.2.7 on 2025-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='use_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='prompthistory',
            unique_together={('prompt_text', 'model_used', 'quality_used', 'negative_prompt_used')},
        ),
    ]
