# Generated by Django 4.2.7 on 2025-10-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_prompthistory_last_used_at_prompthistory_use_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_generated', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
