# Generated by Django 4.2.7 on 2025-10-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality_type', models.CharField(choices=[('fast', 'Быстрое'), ('medium', 'Среднее'), ('high', 'Высокое')], max_length=20)),
                ('steps', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('guidance_scale', models.FloatField(default=7.5)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('translated_prompt', models.TextField(blank=True)),
                ('model_used', models.CharField(max_length=100)),
                ('quality_used', models.CharField(max_length=20)),
                ('negative_prompt_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_images/')),
                ('model_used', models.CharField(max_length=100)),
                ('quality_used', models.CharField(max_length=20)),
                ('negative_prompt_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_generator.task')),
            ],
        ),
    ]
